### ISSUE TITLE
errors trying to use docker image

### ISSUE THREAD

**Issue by mgaitan** [mdelapenya/junit2otlp#86]
I'm trying to send data of 2 junit files  to Honeycomb using the docker image and I get two differents errors. 

```
$ cat junit_app_endpoints_tests_naruto.xml | docker run --rm -i --volume "$(pwd):/opt/projectname" --env OTEL_EXPORTER_OTLP_ENDPOINT="https://api.honeycomb.io:443/v1/traces" --env OTEL_EXPORTER_OTLP_HEADERS="x-honeycomb-team=$HONEY_TOKEN,x-honeycomb-dataset=ci_results" mdelapenya/junit2otlp:latest --service-name naruto --trace-name pr17134 --repository-path "/opt/projectname"
2023/06/02 14:43:36 failed to read from pipe: bufio.Scanner: token too long
```
This is a 4.7mb xml 

The second attempt with a 22kb junit file the error is different

```
$ cat reruns_app_endpoints_tests_naruto.xml | docker run --rm -i --volume "$(pwd):/opt/projectname" --env OTEL_EXPORTER_OTLP_ENDPOINT="https://api.honeycomb.io:443/v1/traces" --env OTEL_EXPORTER_OTLP_HEADERS="x-honeycomb-team=$HONEY_TOKEN,x-honeycomb-dataset=ci_results" mdelapenya/junit2otlp:latest --service-name naruto --trace-name pr17134-rerun --repository-path "/opt/projectname"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x86961e0]

goroutine 1 [running]:
main.(*GitScm).contributeAttributes(0x0)
	/go/src/github.com/mdelapenya/junit2otlp/git.go:99 +0xe0
main.createTracesAndSpans({0x88e5860, 0xac32028}, {0xff961e8c, 0x6}, 0xacb4180, {0xb031920, 0x1, 0x1})
	/go/src/github.com/mdelapenya/junit2otlp/main.go:65 +0x112
main.Main({0x88e5860, 0xac32028}, {0x88e21d8, 0x8d6a470})
	/go/src/github.com/mdelapenya/junit2otlp/main.go:299 +0x95f
main.main()
	/go/src/github.com/mdelapenya/junit2otlp/main.go:305 +0x8c
```

**Comment by mdelapenya** [comment]
Thanks for reporting this issue. I'm on parental leave atm, but will take a look at it asap.

If you could share the test file, the repro case would be much accurate 🙏

**Comment by mdelapenya** [comment]
Hey @mgaitan I can guess the execution has access to a git repo, right? Reading the panic error seems to point to the git code (L99), saying that the git provider is not set: https://github.com/mdelapenya/junit2otlp/blob/c715e3f46d8ec6b308bf8e8a266d9b3a44dc90a2/git.go#L99

For some reason, the SCM provider is not accessing a git repo: https://github.com/mdelapenya/junit2otlp/blob/c715e3f46d8ec6b308bf8e8a266d9b3a44dc90a2/scm.go#L31

For running outside a CI, local execution, please check this method: https://github.com/mdelapenya/junit2otlp/blob/c715e3f46d8ec6b308bf8e8a266d9b3a44dc90a2/scm.go#L149. You probably need to set the right env vars. See https://github.com/mdelapenya/junit2otlp#local-execution

Could you check that?
